### ISSUE TITLE
no file descriptor passed

### ISSUE THREAD

**Issue by stackpivot** [Merovius/srvfb#1]
When I am executing the binary it says:

```
./srvfb -device /dev/fb0                                                                               
2018/12/03 17:04:25 no file descriptor passed by service manager and no -listen set
```

**Comment by martialgarchery** [comment]
same for me

**Comment by Merovius** [comment]
@stackpivot The error message should probably be improved. You either have to provide an address to listen on via e.g. `-listen :1234`, or start it via systemd socket activation (with the unit files in contrib/).

@martialgarchery You do have to have it running on the remarkable itself first, so it can proxy.

I'll improve the docs on this :)
