### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Eeems** [Merovius/srvfb#20]
Hey, could you add a license file so other developers can know what they can, and cannot do with your code?

**Comment by Merovius** [comment]
There's a [license section in the README](https://github.com/Merovius/srvfb#license) and there should be a license header in every file. Apache 2.0.

**Comment by Eeems** [comment]
> There's a [license section in the README](https://github.com/Merovius/srvfb#license) and there should be a license header in every file. Apache 2.0.

@Merovius Thanks! One note on this, Github expects a separate LICENSE file so that it can link to it in the sidebar (and guess at which license it is). You might want to split that out, but that's up to you.

**Comment by Merovius** [comment]
Yeah, I realized. I might do so later in any case. FWIW, I find this licensing stuff onerous and was trying to be as sweepingly clear as possible :) But I guess if githubs heuristics need it, why not.
