### ISSUE TITLE
Download PNG

### ISSUE THREAD

**Issue by Merovius** [Merovius/srvfb#9]
Because we use `x-mixed-replace`, it's not possible to save the streamed images (chrome ends up in an endless download). We should provide a button to download a screenshot.

**Comment by torwag** [comment]
Firefox screenshot function works, albeit with the limitation that it is not the actual streamed image. 
Saving the image firefox seems to have the same trouble as chrome

**Comment by Merovius** [comment]
In 496783e8b6db2ef5fbd4d6a6311b4e7676ef849c I added a route to download the PNG, so I guess I'll close this for now :) Exposing that in a better way can be part of #4
